/**
 * UnitDownIAPPlugin.m
 *
 * This file is intentionally minimal.
 *
 * In Capacitor 8 the CAP_PLUGIN macro only adds CAPBridgedPlugin protocol
 * conformance to a class category — it does NOT auto-register the plugin.
 * Registration only happens if the class name appears in capacitor.config.json's
 * `packageClassList`, which is generated by `npx cap sync` from npm packages
 * only.  Local plugins in ios/App/App/ are never in that list.
 *
 * UnitDownIAPPlugin is therefore:
 *   - Registered explicitly in ViewController.swift via
 *     bridge?.registerPluginInstance(UnitDownIAPPlugin())
 *   - Conforms to CAPBridgedPlugin directly in UnitDownIAPPlugin.swift
 *     (identifier, jsName, pluginMethods properties)
 *
 * The CAP_PLUGIN macro has been removed from this file to avoid duplicate
 * ObjC category method implementations conflicting with the Swift properties.
 * This file is kept in the Xcode project for historical continuity and can be
 * safely removed if desired.
 */
