/**
 * UnitDownIAPPlugin.swift
 *
 * Capacitor plugin that bridges StoreKit 2 purchases to the JavaScript layer.
 *
 * Registration note (Capacitor 8 + SPM):
 *   Capacitor 8 discovers plugins exclusively via `capacitor.config.json`'s
 *   `packageClassList`, which is auto-generated by `npx cap sync` from npm
 *   packages only.  Local plugins (files inside ios/App/App/) are never in
 *   that list, so this class is explicitly registered by ViewController.swift
 *   via `bridge?.registerPluginInstance(UnitDownIAPPlugin())` inside
 *   `capacitorDidLoad()`.
 *
 *   CAPBridgedPlugin conformance is declared here in Swift so the class
 *   satisfies the `CAPPlugin & CAPBridgedPlugin` type alias (`CapacitorPlugin`)
 *   required by `registerPluginInstance`.
 *
 * Xcode setup (once, outside Replit):
 *   1. Both this file AND UnitDownIAPPlugin.m must be in the App target.
 *   2. Enable "In-App Purchase" capability on the App target.
 *   3. Create product com.unitdown.subscription.monthly in App Store Connect
 *      as an Auto-Renewable Subscription in a subscription group.
 *   4. Run: npx cap sync
 */

import Capacitor
import StoreKit

@objc(UnitDownIAPPlugin)
public class UnitDownIAPPlugin: CAPPlugin, CAPBridgedPlugin {

    // MARK: - CAPBridgedPlugin

    public let identifier = "UnitDownIAPPlugin"
    public let jsName = "UnitDownIAP"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "getProducts", returnType: "promise"),
        CAPPluginMethod(name: "purchaseProduct", returnType: "promise"),
        CAPPluginMethod(name: "restoreTransactions", returnType: "promise"),
        CAPPluginMethod(name: "finishTransaction", returnType: "promise"),
    ]

    // MARK: - getProducts

    @objc func getProducts(_ call: CAPPluginCall) {
        guard let productIds = call.getArray("productIds", String.self), !productIds.isEmpty else {
            call.reject("productIds array is required")
            return
        }

        Task {
            do {
                let products = try await Product.products(for: Set(productIds))
                let mapped = products.map { p -> [String: Any] in
                    return [
                        "productId": p.id,
                        "title": p.displayName,
                        "description": p.description,
                        "price": p.displayPrice,
                        "priceAsDecimal": NSDecimalNumber(decimal: p.price).doubleValue,
                        "currencyCode": p.priceFormatStyle.currencyCode
                    ]
                }
                call.resolve(["products": mapped])
            } catch {
                call.reject("Failed to fetch products: \(error.localizedDescription)")
            }
        }
    }

    // MARK: - purchaseProduct

    @objc func purchaseProduct(_ call: CAPPluginCall) {
        guard let productId = call.getString("productId") else {
            call.reject("productId is required")
            return
        }

        Task {
            do {
                let products = try await Product.products(for: [productId])
                guard let product = products.first else {
                    call.reject("Product not found: \(productId)")
                    return
                }

                let result = try await product.purchase()

                switch result {
                case .success(let verification):
                    switch verification {
                    case .verified(let transaction):
                        call.resolve([
                            "transactionId": String(transaction.id),
                            "productId": transaction.productID,
                            "state": "purchased"
                        ])
                    case .unverified(_, let error):
                        call.reject("Purchase unverified: \(error.localizedDescription)")
                    }
                case .userCancelled:
                    call.resolve([
                        "transactionId": "",
                        "productId": productId,
                        "state": "cancelled"
                    ])
                case .pending:
                    call.resolve([
                        "transactionId": "",
                        "productId": productId,
                        "state": "deferred"
                    ])
                @unknown default:
                    call.reject("Unknown purchase result")
                }
            } catch {
                call.reject("Purchase failed: \(error.localizedDescription)", "PURCHASE_ERROR", error)
            }
        }
    }

    // MARK: - restoreTransactions

    @objc func restoreTransactions(_ call: CAPPluginCall) {
        Task {
            var transactions: [[String: Any]] = []

            for await verification in Transaction.currentEntitlements {
                switch verification {
                case .verified(let transaction):
                    transactions.append([
                        "transactionId": String(transaction.id),
                        "productId": transaction.productID,
                        "state": transaction.revocationDate == nil ? "restored" : "revoked"
                    ])
                case .unverified:
                    break
                }
            }

            call.resolve(["transactions": transactions])
        }
    }

    // MARK: - finishTransaction

    @objc func finishTransaction(_ call: CAPPluginCall) {
        guard let transactionIdStr = call.getString("transactionId"),
              let transactionId = UInt64(transactionIdStr) else {
            call.resolve()
            return
        }

        Task {
            for await verification in Transaction.all {
                if case .verified(let transaction) = verification, transaction.id == transactionId {
                    await transaction.finish()
                    break
                }
            }
            call.resolve()
        }
    }
}
