/**
 * UnitDownIAPPlugin.swift
 *
 * Capacitor plugin that bridges StoreKit 2 purchases to the JavaScript layer.
 *
 * Registration note (Capacitor 8 + SPM):
 *   Capacitor 8 discovers plugins exclusively via `capacitor.config.json`'s
 *   `packageClassList`, which is auto-generated by `npx cap sync` from npm
 *   packages only.  Local plugins (files inside ios/App/App/) are never in
 *   that list, so this class is explicitly registered by ViewController.swift
 *   via `bridge?.registerPluginInstance(UnitDownIAPPlugin())` inside
 *   `capacitorDidLoad()`.
 *
 *   CAPBridgedPlugin conformance is declared here in Swift so the class
 *   satisfies the `CAPPlugin & CAPBridgedPlugin` type alias (`CapacitorPlugin`)
 *   required by `registerPluginInstance`.
 *
 * Xcode setup (once, outside Replit):
 *   1. Both this file AND UnitDownIAPPlugin.m must be in the App target.
 *   2. Enable "In-App Purchase" capability on the App target.
 *   3. Create product com.unitdown.subscription.monthly in App Store Connect
 *      as an Auto-Renewable Subscription in a subscription group.
 *   4. Attach the subscription to app version 1.0.1 under
 *      "In-App Purchases and Subscriptions" in App Store Connect.
 *   5. Run: npx cap sync
 */

import Capacitor
import StoreKit

@objc(UnitDownIAPPlugin)
public class UnitDownIAPPlugin: CAPPlugin, CAPBridgedPlugin {

    // MARK: - CAPBridgedPlugin

    public let identifier = "UnitDownIAPPlugin"
    public let jsName = "UnitDownIAP"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "getProducts", returnType: "promise"),
        CAPPluginMethod(name: "purchaseProduct", returnType: "promise"),
        CAPPluginMethod(name: "restoreTransactions", returnType: "promise"),
        CAPPluginMethod(name: "finishTransaction", returnType: "promise"),
    ]

    // MARK: - Helpers

    private var environment: String {
        let isSimulator = ProcessInfo.processInfo.environment["SIMULATOR_DEVICE_NAME"] != nil
        if isSimulator { return "simulator" }
        let isSandbox = Bundle.main.appStoreReceiptURL?.lastPathComponent == "sandboxReceipt"
        return isSandbox ? "sandbox/TestFlight" : "production"
    }

    private var bundleId: String {
        return Bundle.main.bundleIdentifier ?? "unknown"
    }

    // MARK: - getProducts

    @objc func getProducts(_ call: CAPPluginCall) {
        guard let productIds = call.getArray("productIds", String.self), !productIds.isEmpty else {
            call.reject("productIds array is required")
            return
        }

        let env = environment
        let bid = bundleId
        print("⚡️ [UnitDownIAP] getProducts — env:\(env)  bundleId:\(bid)  requesting:\(productIds)")

        Task {
            do {
                let products = try await Product.products(for: Set(productIds))

                if products.isEmpty {
                    print("⚡️ [UnitDownIAP] getProducts — StoreKit returned 0 products.")
                    print("⚡️ [UnitDownIAP]   Checklist:")
                    print("⚡️ [UnitDownIAP]   1. App Store Connect → your app → version 1.0.1 → 'In-App Purchases and Subscriptions' → is '\(productIds.first ?? "?")' listed?")
                    print("⚡️ [UnitDownIAP]   2. Bundle ID in App Store Connect matches '\(bid)'?")
                    print("⚡️ [UnitDownIAP]   3. Subscription status is 'Waiting for Review', 'Ready to Submit', or 'Approved'?")
                    print("⚡️ [UnitDownIAP]   4. Sandbox Apple ID is configured in Settings → App Store → Sandbox Account?")
                    call.resolve(["products": [] as [[String: Any]]])
                    return
                }

                let mapped = products.map { p -> [String: Any] in
                    return [
                        "productId": p.id,
                        "title": p.displayName,
                        "description": p.description,
                        "price": p.displayPrice,
                        "priceAsDecimal": NSDecimalNumber(decimal: p.price).doubleValue,
                        "currencyCode": p.priceFormatStyle.currencyCode
                    ]
                }
                print("⚡️ [UnitDownIAP] getProducts — StoreKit returned \(products.count) product(s): \(products.map { "\($0.id)=\($0.displayPrice)" }.joined(separator: ", "))")
                call.resolve(["products": mapped])
            } catch {
                print("⚡️ [UnitDownIAP] getProducts — error: \(error.localizedDescription)")
                call.reject("Failed to fetch products: \(error.localizedDescription)")
            }
        }
    }

    // MARK: - purchaseProduct

    @objc func purchaseProduct(_ call: CAPPluginCall) {
        guard let productId = call.getString("productId") else {
            call.reject("productId is required")
            return
        }

        let env = environment
        let bid = bundleId
        print("⚡️ [UnitDownIAP] purchaseProduct — env:\(env)  bundleId:\(bid)  productId:\(productId)")

        Task {
            do {
                let products = try await Product.products(for: [productId])
                print("⚡️ [UnitDownIAP] purchaseProduct — StoreKit lookup returned \(products.count) product(s) for '\(productId)'")
                guard let product = products.first else {
                    print("⚡️ [UnitDownIAP] purchaseProduct — product '\(productId)' not found in StoreKit. See getProducts checklist above.")
                    call.reject("Product not found: \(productId)")
                    return
                }

                let result = try await product.purchase()

                switch result {
                case .success(let verification):
                    switch verification {
                    case .verified(let transaction):
                        print("⚡️ [UnitDownIAP] purchaseProduct — SUCCESS txId:\(transaction.id) state:purchased")
                        call.resolve([
                            "transactionId": String(transaction.id),
                            "productId": transaction.productID,
                            "state": "purchased"
                        ])
                    case .unverified(_, let error):
                        print("⚡️ [UnitDownIAP] purchaseProduct — unverified: \(error.localizedDescription)")
                        call.reject("Purchase unverified: \(error.localizedDescription)")
                    }
                case .userCancelled:
                    print("⚡️ [UnitDownIAP] purchaseProduct — user cancelled")
                    call.resolve([
                        "transactionId": "",
                        "productId": productId,
                        "state": "cancelled"
                    ])
                case .pending:
                    print("⚡️ [UnitDownIAP] purchaseProduct — deferred (parental approval pending)")
                    call.resolve([
                        "transactionId": "",
                        "productId": productId,
                        "state": "deferred"
                    ])
                @unknown default:
                    call.reject("Unknown purchase result")
                }
            } catch {
                print("⚡️ [UnitDownIAP] purchaseProduct — threw: \(error.localizedDescription)")
                call.reject("Purchase failed: \(error.localizedDescription)", "PURCHASE_ERROR", error)
            }
        }
    }

    // MARK: - restoreTransactions

    @objc func restoreTransactions(_ call: CAPPluginCall) {
        print("⚡️ [UnitDownIAP] restoreTransactions — env:\(environment)  bundleId:\(bundleId)")
        Task {
            var transactions: [[String: Any]] = []

            for await verification in Transaction.currentEntitlements {
                switch verification {
                case .verified(let transaction):
                    transactions.append([
                        "transactionId": String(transaction.id),
                        "productId": transaction.productID,
                        "state": transaction.revocationDate == nil ? "restored" : "revoked"
                    ])
                case .unverified:
                    break
                }
            }

            print("⚡️ [UnitDownIAP] restoreTransactions — found \(transactions.count) entitlement(s): \(transactions.map { $0["productId"] as? String ?? "?" }.joined(separator: ", "))")
            call.resolve(["transactions": transactions])
        }
    }

    // MARK: - finishTransaction

    @objc func finishTransaction(_ call: CAPPluginCall) {
        guard let transactionIdStr = call.getString("transactionId"),
              let transactionId = UInt64(transactionIdStr) else {
            call.resolve()
            return
        }

        Task {
            for await verification in Transaction.all {
                if case .verified(let transaction) = verification, transaction.id == transactionId {
                    await transaction.finish()
                    print("⚡️ [UnitDownIAP] finishTransaction — finished txId:\(transactionId)")
                    break
                }
            }
            call.resolve()
        }
    }
}
